export interface IModuleSchema {
        DisplayName: String,
        showSn: boolean,
        showItemNo: boolean,
        Desc1: boolean,
        Mac0: boolean,
        Mac1: boolean,
       // Mac2: string,
        Uuid0: boolean,
        Uuid1: boolean,
        Imei0: boolean,
        Imei1: boolean,
        //imei2: string,
        //imei3: string,
        ParentSn: boolean,
        ParentId?: boolean,
        IsParent: boolean,        
}